= Samples
:toc:
:toc-placement: preamble
:sectanchors:

Here are some samples about Java EE technologies (JPA in Java SE is covered as well). They serve two purposes:

* give a head start (if you want a correctly configured project as a basis for work); and
* illustrate link:++https://github.com/oliviercailloux/java-course/tree/master/Best practices/++[“best” practices] in concrete, simple cases.

To access these samples with Eclipse, I recommend to first git clone this repository, then, from Eclipse, use `Import… Existing Projects`.

All projects use Maven and are designed for maximal compatibility. They should run on any Java EE 7 server. (Tested with GlassFish only.)

== The sample projects
=== JavaEE-Servlets
Just one servlet that says “Hello, world.”.

=== JavaEE-Inject-Servlets
Illustrates CDI and servlets. Just one servlet that says “Hello, world.” thanks to a managed bean, injected into the servlet.

=== JavaEE-Inject-Servlets-Conversation
Illustrates usage of CDI conversations. (To use it, start by querying ViewConversationServlet, because of a possible https://issues.jboss.org/browse/WELD-2243[Weld bug].)

=== JavaEE-Inject-Produces-Servlets
Shows usage of CDI (Injection of managed beans) and producers together with simple servlets. This will be useful only if you want to know about producers. Otherwise, check a simpler CDI sample (see <<other-samples>>).

* The `advanced` package illustrates dynamic instance creation. That advanced servlet also has a question that you might want to solve as an exercice (look at the Javadoc).

=== JavaEE-Inject-Produces-Servlets-JSF
Same as JavaEE-Inject-Produces-Servlets with a supplementary very simple JSF page that calls the producer.

=== JavaEE-JPA-Inject-Servlets
A simple JPA project, using a single entity, simple CDI managed beans and two simple servlets (posting items and getting items).

* The `advanced` package illustrates different transaction management approaches.

[[JavaEE-JPA-Inject-Servlets-JUnit]]
=== JavaEE-JPA-Inject-Servlets-JUnit
Illustrates (the awkwardness of) JUnit-testing servlets that use CDI. This sample uses standalone Weld. Not recommended: see https://github.com/oliviercailloux/java-course/tree/master/Best%20practices/TestingEE.adoc#Weld-SE[Weld-SE] in my Best practices folder.

=== JavaEE-JPA-JSF
A simple JPA project with two simple JSF pages. Also illustrated: https://github.com/oliviercailloux/java-course/tree/master/Best%20practices/JPA.adoc#metamodel[typesafe JPA queries], https://github.com/oliviercailloux/java-course/tree/master/Best%20practices/JSF.adoc#multifield[multi field validation].

=== JavaSE-JUL-JPA-Hib-H2
A simple JavaSE project featuring JPA, starring Hibernate as a JPA provider and H2 as a DB provider. This sample project uses JUL as a logger (contradicting my https://github.com/oliviercailloux/java-course/tree/master/Best%20practices/Logging.adoc#logging-choice[own preference]).

[[other-samples]]
== Other samples
Here are some sources for more samples.

* https://github.com/wildfly/quickstart[wildfly]:
** check out, for example, https://github.com/wildfly/quickstart/tree/10.x/cdi-injection[cdi-injection] for a very simple use of CDI.
* https://github.com/javaee-samples/javaee7-samples[Java EE 7 Samples]
* GlassFish comes with (mostly elaborated) samples (in the `samples` subdir of GlassFish), also available through https://svn.java.net/svn/glassfish-samples~svn/trunk/ws/javaee7/[svn].
* To access the samples with Eclipse: I recommend to first git clone (or d/l) the repository, then use Eclipse Maven import.

