= Samples
:toc:
:toc-placement: preamble
:sectanchors:

Here are some samples about Java EE technologies (JPA in Java SE is covered as well). They serve two purposes:

* give a head start (if you want a correctly configured project as a basis for work); and
* illustrate “best” practices in concrete, simple cases.

To access these samples with Eclipse, I recommend to first git clone this repository, then, from Eclipse, use `Import… Existing Projects`.

Scroll down for the discussion about (what I consider to be) best practices.

== The sample projects
All projects use Maven and are designed for maximal compatibility. They should run on any Java EE 7 server. (Tested with GlassFish only.)

=== JavaEE-Servlets
Just one servlet that says “Hello, world.”.

=== JavaEE-Inject-Servlets
Illustrates CDI and servlets. Just one servlet that says “Hello, world.” thanks to a managed bean, injected into the servlet.

=== JavaEE-Inject-Servlets-Conversation
Illustrates usage of CDI conversations. (To use it, start by querying ViewConversationServlet, because of a possible https://issues.jboss.org/browse/WELD-2243[Weld bug].)

=== JavaEE-Inject-Produces-Servlets
Shows usage of CDI (Injection of managed beans) and producers together with simple servlets. This will be useful only if you want to know about producers. Otherwise, check a simpler CDI sample (see <<other-samples>>).

* The `advanced` package illustrates dynamic instance creation. That
advanced servlet also has a question that you might want to solve as an
exercice (look at the Javadoc).

=== JavaEE-Inject-Produces-Servlets-JSF
Same as JavaEE-Inject-Produces-Servlets with a supplementary very simple
JSF page that calls the producer.

=== JavaEE-JPA-Inject-Servlets
A simple JPA project, using a single entity, simple CDI managed beans
and two simple servlets (posting items and getting items).

* The `advanced` package illustrates different transaction management
approaches.

=== JavaEE-JPA-JSF
A simple JPA project with two simple JSF pages.

* Also illustrated: <<metamodel, typesafe JPA queries>>.
* Also illustrated: <<multifield, multi field validation>>.

=== JavaSE-JUL-JPA-Hib-H2
A simple JavaSE project featuring JPA, starring Hibernate as a JPA
provider and H2 as a DB provider. This sample project uses JUL as a
logger (contradicting my <<logging-choice, own preference>>).

== Maven best practices
=== Encoding
Include property
`<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>` to
ensure platform-independent behavior (and get rid of the warning Maven
prints otherwise).

=== Java version
Include properties:
`<maven.compiler.source>1.8</maven.compiler.source> <maven.compiler.target>1.8</maven.compiler.target>`
(or adjust to the desired java version) to indicate which java version
you develop in (and for). This is
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html[officially
supported] and is thus to be preferred to the more verbose explicit
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html[configuration]
of the `maven-compiler-plugin`.

=== Do not require web descriptor
Web applications do not require a web descriptor (the `web.xml` file
that goes in the `WEB-INF` folder). Maven however required it by default
when asked to package a war file. If you do not need a web descriptor,
make your project as clean as possible and do not include one! Rather,
include the property `<failOnMissingWebXml>false</failOnMissingWebXml>`
in your `pom.xml`.

* [Note 1: As of Release 3.0.0 of the Apache Maven WAR Plugin, this is
no more necessary: “The default value for failOnMissingWebXml has been
changed from true to false.”
(https://maven.apache.org/plugins/maven-war-plugin/index.html[source]).
However including the property anyway improves your project
compatibility. See also
http://svn.apache.org/viewvc/maven/plugins/trunk/maven-war-plugin/src/main/java/org/apache/maven/plugins/war/WarMojo.java?view=log[source
code history],
http://svn.apache.org/viewvc/maven/plugins/tags/[releases].]
* [Note 2: Web applications do not require a web descriptor any more
since more than 10 years, since Servlet 2.5 MR 5 (see JSR 340 Servlet
3.1
http://download.oracle.com/otn-pub/jcp/servlet-3_1-fr-eval-spec/servlet-3_1-final.pdf[spec],
A.7.6 and 10.13).]

== JPA best practices
=== Use delimited identifiers
Tell JPA to use delimited identifiers (see the object/relational xml
mapping file, `orm.xml`, in the JPA samples). (See JSR 338 JPA 2.1
link:[spec], section 2.13.) JPA will then “delimit” (quote) all SQL
identifiers, thus avoiding conflicts with e.g. table names that are also
SQL keywords. Note that this render identifiers case sensitive.
Delimited identifiers is off by default and may cause nasty problems,
especially because SQL keywords differ by vendor (and it’s hard to keep
track of all of them, see e.g.
http://hsqldb.org/doc/guide/lists-app.html[here] or
https://www.drupal.org/node/141051[here]). A typical problem with non
delimited identifiers occurs when using an entity named `User`: this may
work on some DBMS and fail at runtime on others.

[[metamodel]]
=== Metamodel generator for typesafe JPA queries
To generate the metamodel for use with typesafe Criteria queries,
suffices to include a metamodel generator in your classpath
(http://hibernate.org/orm/tooling/[doc]). Set it to `<provided>` scope
as your code does not depend on it at runtime.

* For correct integration in Eclipse (neon, Java EE version), I have
installed
`Maven Integration for Eclipse JDT Annotation Processor Toolkit`, then
in the project settings, Maven / Annotation Processing, selected:
Automatically configure JDT APT. (Eclipse also has an internal option to
generate the metamodel, see the project options at JPA / Canonical
metamodel, but I don’t use that as it hinders compatibility of the
project with other IDEs.)

== JSF best practices
[[multifield]]
=== Multiple field validation
Sometimes the validation logic requires knowledge of the value of
multiple fields. (Example: required `start` ≤ `end`, where `start` and
`end` are two request parameters.) In such case I consider the usual JSF
validation approach (namely, by treating the problem in the JSF
validation phase) inelegant, because it is designed for single-field
validation. I prefer to use case-based navigation in the action phase.
Some may disagree, see e.g. BalusC, “JSF ajax/action/listener methods
are semantically the wrong place to do validation”
http://stackoverflow.com/a/5897183/859604[here] and an alternative
proposal
http://balusc.omnifaces.org/2007/12/validator-for-multiple-fields.html[here].

== Logging best practices
[[logging-choice]]
=== Framework
One of the PITA in Java world is the multiplicity of logging framework.
My personal choice is to go for JUL for Java EE projects and SLF4J plus logback for Java SE projects.

[[other-samples]]
== Other samples
Here are some sources for more samples.

* https://github.com/wildfly/quickstart[wildfly]:
** check out, for example, https://github.com/wildfly/quickstart/tree/10.x/cdi-injection[cdi-injection] for a very simple use of CDI.
* GlassFish comes with (mostly elaborated) samples (in the `samples` subdir of GlassFish), also available through https://svn.java.net/svn/glassfish-samples~svn/trunk/ws/javaee7/[svn].
* To access the samples with eclipse: I recommend to first git clone (or d/l) the repository, then use eclipse Maven import.

